### ISSUE TITLE
Issues exporting the ocean mask

### ISSUE THREAD

**Issue by steveabraham** [Treer/minecraft-map#5]
Not sure if this is the right place to ask this, apologies if not.

I've been trying to run your modified Amidst in order export the ocean mask, but it just crashes on launch. I've tried on macOS with the supplied command line, and also on Windows with the compiled .exe, but no luck with either option.

The error output is as follows:
https://gist.github.com/steveabraham/bf093abe84792669da488ffeafc07529

**Comment by Treer** [comment]
This happens to me as well now, so not sure if it's been introduced by jre8 or newer versions of Minecraft, but you can rest assured it is reproducible :)

I'll look into it, though not sure when. Judging by [activity on the Amidst4 project](https://github.com/toolbox4minecraft/amidst/issues/395) I expect Minecraft 1.13 is about to break everything.
Edit: for AmidstExporter, Minecraft 1.11 already broke everything, so you need to use it with a 1.10 profile

**Comment by Treer** [comment]
Can you confirm that [AmidstExporter v1.45](https://github.com/Treer/AmidstExporter/releases) fixes this issue?

**Comment by steveabraham** [comment]
Worked perfectly, yes, thank you!
